apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: techtrends
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: techtrends
  ports:
    - protocol: {{ .Values.service.protocol }}
      port:  {{ .Values.service.port }}
      targetPort:  {{ .Values.service.targetPort }}