apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: techtrends
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: solutions/helm/nginx-deployment
    repoURL: https://github.com/udacity/nd064_course_1
    targetRevision: HEAD