apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: techtrends
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: project/helm/nginx-deployment
    repoURL: https://github.com/alemag1986/Udacity_TechTrends
    targetRevision: HEAD